hepsi: derle calistir

derle:
	g++ -I ./include/ -c ./src/Dugum.cpp -o ./lib/Dugum.o
	g++ -I ./include/ -c ./src/LinkedList.cpp -o ./lib/LinkedList.o
	g++ -I ./include/ ./lib/Dugum.o ./lib/LinkedList.o ./src/Test.cpp -o ./bin/Program

calistir:
	./bin/Program